---
title: "&#39;Catch&#39;는 &#39;Try&#39; 문 내에서 &#39;Finally&#39; 뒤에 사용할 수 없습니다. | Microsoft Docs"
ms.custom: ""
ms.date: "11/16/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "devlang-visual-basic"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "vbc30379"
  - "bc30379"
helpviewer_keywords: 
  - "BC30379"
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
caps.latest.revision: 8
caps.handback.revision: 8
author: "stevehoag"
ms.author: "shoag"
manager: "wpickett"
---
# &#39;Catch&#39;는 &#39;Try&#39; 문 내에서 &#39;Finally&#39; 뒤에 사용할 수 없습니다.
`Catch` 문이 코드에서 `Try` 문 블록을 끝내는 `Finally` 뒤에 나타납니다.`Catch`는 `Try...Catch...Finally` 문 블록 내에서 사용해야 합니다.  
  
 **오류 ID:** BC30379  
  
### 이 오류를 해결하려면  
  
1.  `Catch` 문을 코드의 더 적절한 위치로 이동합니다.  
  
## 참고 항목  
 [Try...Catch...Finally Statement](../Topic/Try...Catch...Finally%20Statement%20\(Visual%20Basic\).md)   
 [Visual Basic의 구조적 예외 처리 개요](http://msdn.microsoft.com/ko-kr/bb81af80-a735-4873-9711-6151a48e418a)